name: Daily DSA Problem to Telegram

on:
  schedule:
    - cron: '30 2 * * *'     # 7:30 AM IST
  workflow_dispatch:

jobs:
  send-problem:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install requests
        run: pip install requests
      
      - name: Send Daily Problem
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_problem.py
